source 'https://rubygems.org'
gem 'ruby-filemagic'
gem 'sanitize'
gem 'sinatra'
gem 'sinatra-browserid', :git => 'https://github.com/passcod/sinatra-browserid.git'
gem 'nokogiri'
gem 'puma'
gem 'sqlite3'
gem 'pony'
gem 'madeleine', :git => 'https://github.com/ghostganz/madeleine.git'
gem 'classifier'
gem 'htmlentities'
gem 'gsl'
gem 'mechanize'
gem 'kramdown'
gem 'sprockets', '~> 2.0'
gem 'therubyracer'  # not necessary when on Windows or having node installed
gem 'uglifier'
gem 'cssminify'
