source 'https://rubygems.org'
gem 'ruby-filemagic'
gem 'sanitize'
gem 'sinatra'
gem 'sinatra-browserid', :git => 'https://github.com/passcod/sinatra-browserid.git'
gem 'nokogiri'
gem 'puma'
gem 'sqlite3'
gem 'pony'
gem 'madeleine'
gem 'classifier'
gem 'htmlentities'
gem 'RedCloth'
gem 'gsl'
