source 'https://rubygems.org'
gem 'sanitize'
gem 'sinatra'
gem 'sinatra-browserid', :git => 'https://github.com/sch1zo/sinatra-browserid'
gem 'nokogiri'
gem 'puma'
gem 'sqlite3'
gem 'pony'
gem 'classifier'
gem 'htmlentities'
#gem 'gsl'
gem 'mechanize'
gem 'kramdown'
gem 'sprockets', '~> 2.0'
gem 'therubyracer'  # not necessary when on Windows or having node installed
gem 'uglifier'
gem 'cssminify'
gem 'emk-sinatra-url-for'
gem 'http'
gem 'thread'